# Generated by Django 4.1.5 on 2023-01-27 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="address",
            fields=[
                (
                    "address_id",
                    models.AutoField(
                        db_column="Address ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_column="City_Town", max_length=100, unique=True
                    ),
                ),
                (
                    "state_region",
                    models.CharField(db_column="State_Region", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="classroom",
            fields=[
                (
                    "classroom_id",
                    models.AutoField(
                        db_column="Room ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "classroom_name",
                    models.CharField(db_column="Room Name", max_length=100),
                ),
                ("subject_id", models.JSONField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("class_time", models.CharField(max_length=10)),
                ("student_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="student_registeraiton",
            fields=[
                (
                    "student_id",
                    models.AutoField(
                        db_column="Student_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "mail",
                    models.CharField(db_column="Email", max_length=50, unique=True),
                ),
                (
                    "phone",
                    models.CharField(db_column="Phone", max_length=15, unique=True),
                ),
                ("password", models.CharField(db_column="Password", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="subject",
            fields=[
                (
                    "subject_id",
                    models.AutoField(
                        db_column="Subject_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(db_column="Subject_Name", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="teacher",
            fields=[
                (
                    "teacher_id",
                    models.AutoField(
                        db_column="Teacher ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, db_column="First_Name", max_length=50),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, db_column="Last_Name", max_length=50),
                ),
                (
                    "phone1",
                    models.CharField(
                        db_column="Personal Phone", max_length=15, unique=True
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True,
                        db_column="Emergency Phone",
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "mail",
                    models.EmailField(db_column="Mail", max_length=100, unique=True),
                ),
                ("classroom", models.JSONField()),
                ("subjects", models.JSONField()),
                ("social_media", models.JSONField()),
                ("age", models.IntegerField()),
                (
                    "address_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, db_column="First_Name", max_length=50),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, db_column="Last_Name", max_length=50),
                ),
                ("phone1", models.CharField(max_length=15, unique=True)),
                (
                    "phone2",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("mail", models.EmailField(max_length=100, unique=True)),
                ("classroom", models.JSONField()),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                (
                    "address_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.address",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.student_registeraiton",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="room_std_teacher",
            fields=[
                (
                    "relation_id",
                    models.AutoField(
                        db_column="Relation_Id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "classroom_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.classroom"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.student_registeraiton",
                    ),
                ),
                (
                    "teacher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.teacher"
                    ),
                ),
            ],
        ),
    ]
